export const data = JSON.parse("{\"key\":\"v-f7eb468c\",\"path\":\"/posts/articles/article-3.html\",\"title\":\"Github进行fork后如何与原仓库同步\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Github进行fork后如何与原仓库同步 实在是……有太多人同时在帮忙修订错别字或优化 xiaolai 的 the-craft-of-selfteaching 了。如果你提交的 pull request 未被接受且得到回复说：“重新fork”，其实是你遇到一个问题： 在你 fork 之后， xiaolai 的仓库又更新了； 但 github 不会自动帮你把 xiaolai 的仓库 同步给你 fork 后的仓库； 导致你提交 pull request 时的版本和 xiaolai 的版本不一致。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://enze5088.github.io/posts/articles/article-3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹拾遗\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Github进行fork后如何与原仓库同步\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Github进行fork后如何与原仓库同步 实在是……有太多人同时在帮忙修订错别字或优化 xiaolai 的 the-craft-of-selfteaching 了。如果你提交的 pull request 未被接受且得到回复说：“重新fork”，其实是你遇到一个问题： 在你 fork 之后， xiaolai 的仓库又更新了； 但 github 不会自动帮你把 xiaolai 的仓库 同步给你 fork 后的仓库； 导致你提交 pull request 时的版本和 xiaolai 的版本不一致。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Github进行fork后如何与原仓库同步\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":3,\"title\":\"merge前的设定\",\"slug\":\"merge前的设定\",\"link\":\"#merge前的设定\",\"children\":[]},{\"level\":3,\"title\":\"merge 的关键命令\",\"slug\":\"merge-的关键命令\",\"link\":\"#merge-的关键命令\",\"children\":[]},{\"level\":2,\"title\":\"PS: 如何优雅的获得上游最新内容?\",\"slug\":\"ps-如何优雅的获得上游最新内容\",\"link\":\"#ps-如何优雅的获得上游最新内容\",\"children\":[]},{\"level\":2,\"title\":\"PPS:\",\"slug\":\"pps\",\"link\":\"#pps\",\"children\":[{\"level\":3,\"title\":\"版本一：fork 后未做任何改动\",\"slug\":\"版本一-fork-后未做任何改动\",\"link\":\"#版本一-fork-后未做任何改动\",\"children\":[]},{\"level\":3,\"title\":\"版本二：fork 后做了改动\",\"slug\":\"版本二-fork-后做了改动\",\"link\":\"#版本二-fork-后做了改动\",\"children\":[]},{\"level\":3,\"title\":\"可能的意外情况：\",\"slug\":\"可能的意外情况\",\"link\":\"#可能的意外情况\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.4,\"words\":2819},\"filePathRelative\":\"posts/articles/article-3.md\",\"excerpt\":\"<h1> Github进行fork后如何与原仓库同步</h1>\\n<p>实在是……有太多人同时在帮忙修订错别字或优化 xiaolai 的 <code>the-craft-of-selfteaching</code> 了。如果你提交的 pull request 未被接受且得到回复说：“重新fork”，其实是你遇到一个问题：</p>\\n<blockquote>\\n<ul>\\n<li>在你 fork 之后， xiaolai 的仓库又更新了；</li>\\n<li>但 github 不会自动帮你把 xiaolai 的仓库 同步给你 fork 后的仓库；</li>\\n<li>导致你提交 pull request 时的版本和 xiaolai 的版本不一致。</li>\\n</ul>\\n</blockquote>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
